var text = "\nBAB I PENDAHULUAN\n\nAlgoritma adalah sekumpulan langkah-langkah sistematis yang disusun\nsecara logis untuk menyelesaikan sebuah masalah dalam pemrograman.\nStruktur data adalah cara menyimpan data secara terorganisir agar\ndapat diakses dan dimodifikasi dengan efisien pada memori komputer.\nKeduanya merupakan fondasi utama dalam membangun sistem perangkat\nlunak yang memiliki performa tinggi serta skalabilitas yang baik.\nTanpa pemahaman algoritma yang kuat, kode akan sulit untuk dibaca.\nSebaliknya, tanpa struktur data yang tepat, program akan menjadi\nsangat lambat dalam memproses informasi yang besar dan kompleks.\n";
var atMethod = text.at(8);
var charAtMethod = text.charAt(10);
var sliceMethod = text.slice(20, -1);
var subStringMethod = text.substring(1, 18);
var splitMethod = text.split("\n");
var joinMethod = splitMethod.join(" ");
var lines = text.split("\n").map(function (line) { return line.trim(); }).filter(Boolean);
console.log('At method:', atMethod);
console.log('\n');
console.log('CharAt method:', charAtMethod);
console.log('\n');
console.log('Slice method:', sliceMethod);
console.log('\n');
console.log('Sub String method:', subStringMethod);
console.log('\n');
console.log('Split method:', splitMethod);
console.log('\n');
console.log('Join method:', joinMethod);
console.log('\n');
console.log('Lines:', lines);
