var text = "\nBAB I PENDAHULUAN\n\nAlgoritma adalah langkah-langkah penyelesaian masalah.\nStruktur data adalah cara menyimpan data.\n";
var atMethod = text.at(8);
var charAtMethod = text.charAt(10);
var sliceMethod = text.slice(20, -1);
var subStringMethod = text.substring(1, 18);
var splitMethod = text.split("\n");
var joinMethod = splitMethod.join(" ");
var lines = text.split("\n").map(function (line) { return line.trim(); }).filter(Boolean);
console.log('At method:', atMethod);
console.log('CharAt method:', charAtMethod);
console.log('Slice method:', sliceMethod);
console.log('Sub String method:', subStringMethod);
console.log('Split method:', splitMethod);
console.log('Join method:', joinMethod);
console.log('Lines:', lines);
