var text = "\nBAB I PENDAHULUAN\n\nAlgoritma adalah langkah-langkah penyelesaian masalah.\nStruktur data adalah cara menyimpan data.\n";
var atMethod = text.at(8);
var charAtMethod = text.charAt(10);
var sliceMethod = text.slice(18, -1);
var subStringMethod = text.substring(18, -1);
var splitMethod = text.split("\n");
var joinMethod = splitMethod.join(" ");
console.log('At method:', atMethod);
console.log('CharAt method:', charAtMethod);
console.log('Slice method:', sliceMethod);
console.log('Sub String method:', subStringMethod);
console.log('Split method:', splitMethod);
console.log('Join method:', joinMethod);
